language: ruby
cache:
  - apt
  - bundler
bundler_args: "--without production --binstubs"
env:
  - RAILS_ENV=test
services:
  - postgresql
addons:
  postgresql: '9.3'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database lunch-ordering-saas_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/