language: ruby
cache:
  - apt
  - bundler
bundler_args: "--without production --binstubs"
env:
  - RAILS_ENV=test
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

# the script that runs your tests
script:
  - bundle exec rspec